### ISSUE TITLE
Homosaurus error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#40] opened 2019-10-23 18:17 UTC
From one of the Homosaurus board members:

Hey KJ

These are errors encountered when I was mistakenly mapping LCSH :)

 Errors/Questions
 Encountered

Most of these errors seem
 to happen when there are terms with blank boxes on right and left -- I’m not sure what that means, end of hierarchy?
In this example for
https://www.digitaltransgenderarchive.net/homosaurus_v2/27851/edit? 

Choosing the yellow option
 will result in an error out--it cannot be saved:

https://www.digitaltransgenderarchive.net/homosaurus_v2/29901/edit?
 Is broken with safer sex parties (http://homosaurus.org/terms/saferSexParties)

https://www.digitaltransgenderarchive.net/homosaurus_v2/18131/edit?
 LCSH Normalization of Deviance errors out

Cant get to LCSH passing because of limit
 of results https://www.digitaltransgenderarchive.net/homosaurus_v2/28271/edit?

Same as
https://www.digitaltransgenderarchive.net/homosaurus_v2/28281/edit?

https://www.digitaltransgenderarchive.net/homosaurus_v2/28151/edit?
 Broken by
Parents of transgender children (http://id.loc.gov/authorities/subjects/sh2016000194)

https://www.digitaltransgenderarchive.net/homosaurus_v2/28681
 PrEP broken by Pre-exposure prophylaxis (http://id.loc.gov/authorities/subjects/sh2017003696)

Older transgender people LCSH
https://www.digitaltransgenderarchive.net/homosaurus_v2/27951/edit?
 Older transgender people (http://id.loc.gov/authorities/subjects/sh2018003006)
 errors out

https://www.digitaltransgenderarchive.net/homosaurus_v2/27421/edit?
 Adding medicalisation (http://homosaurus.org/terms/medicalisation)
 and Medicalization (http://id.loc.gov/authorities/subjects/sh2016000450)
 but errors out

https://www.digitaltransgenderarchive.net/homosaurus_v2/27391/edit?
 Adding metropolitan community church (http://homosaurus.org/terms/metropolitanCommunityChurch)
 and Multiculturalism--Religious aspects--Universal Fellowship of Metropolitan Community Churches (http://id.loc.gov/authorities/subjects/sh2019100804) 
 but errors out

https://www.digitaltransgenderarchive.net/homosaurus_v2/27691/edit?
 Adding Muslim gay men (http://id.loc.gov/authorities/subjects/sh2009009639)goes okay, but Muslim lesbians (http://id.loc.gov/authorities/subjects/sh2018001970) does not work 

​

**Comment by kjrawson** [comment] 2019-10-23 18:17
![pasted image 0](https://user-images.githubusercontent.com/15388345/67422142-e3163780-f59f-11e9-8493-21ffff542294.png)

**Comment by scande3** [comment] 2019-11-05 07:28
- LCSH errors appear to be due to the dataset we have in our cache being older than when those terms were added. (Initial search suggestions come from live LCSH data while the details come from a Blazegraph cache). Can try updating these in the next day or two.

- Unsure of the error of the following as it doesn't seem to error for me: https://www.digitaltransgenderarchive.net/homosaurus_v2/29901/edit?
Is broken with safer sex parties (http://homosaurus.org/terms/saferSexParties)

**Comment by scande3** [comment] 2019-11-05 09:55
Actually refreshed the subjects dataset now. Can you have this user retry these and see if they still experience errors?

Additionally, for the case that their search term doesn't have enough results, they can now search by LCSH URI. For example, searching by "http://id.loc.gov/authorities/subjects/sh85012026" will bring up baseball.

**Comment by brimwats1** [comment] 2019-11-06 14:54
I can confirm that this is fixed on my end!

**Closed as completed** 2019-11-06 15:08 UTC
